# Generated by Django 4.2 on 2023-04-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('taille', models.IntegerField()),
                ('type_fichier', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nombre_fichiers', models.IntegerField()),
                ('taille_totale', models.IntegerField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to=settings.AUTH_USER_MODEL)),
                ('expéditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mizara_app.fichier')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='mizara_app.transfert')),
            ],
        ),
    ]
